name: Lint

on:
  [push, pull_request]:
    paths:
      - '*.py'

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7.4
          architecture: x64
      - name: Checkout PyTorch
        uses: actions/checkout@master
      - name: Run Black
        uses: psf/black@stable
        with:
          options: "--check --verbose --line-length=120"
      - name: Python Pylint GitHub Action
        uses: vcoder4c/git_pylint@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}