name: Lint

on:
  push:
    paths:
      - '*.py'

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.12
          architecture: x64
      - name: Checkout PyTorch
        uses: actions/checkout@master
      - name: Python Pylin GitHub Action
        uses: vcoder4c/git_pylint@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}